force-app/main/default/roles/Admin.role-meta.xml, force-app/main/default/roles/CYC_Humbolt_Coordinator.role-meta.xml, force-app/main/default/roles/CYC_Humbolt_Park_Manager_Director.role-meta.xml, force-app/main/default/roles/CYC_Uptown_Coordinator.role-meta.xml, force-app/main/default/roles/CYC_Uptown_Manager_Directors.role-meta.xml, force-app/main/default/roles/Camp_and_Summer_Tour_Coordinator.role-meta.xml, force-app/main/default/roles/Camp_and_Summer_Tour_Manager_Director.role-meta.xml, force-app/main/default/roles/CircusWork_Onsite_Coordinator.role-meta.xml, force-app/main/default/roles/CircusWork_Onsite_Manager_Director.role-meta.xml, force-app/main/default/roles/MCMF_Programming_Coordinator.role-meta.xml, force-app/main/default/roles/MCMF_Programming_Manager_Director.role-meta.xml, force-app/main/default/roles/Partnerships_Manager_Director.role-meta.xml, force-app/main/default/roles/Walsh_Elementary_Coordinator.role-meta.xml, force-app/main/default/roles/Walsh_Elementary_Manager_Director.role-meta.xml
=> [DevOps Center] Merge WI-010433 to UAT

force-app/main/default/globalValueSets/Race.globalValueSet-meta.xml, force-app/main/default/objects/Child__c/fields/Account__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Age__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Allergies__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Authorized_Pickup__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/CircEsteem_Program__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Class__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Contact__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Date_of_Birth__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/First_Name__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Grade__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Last_Name__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Parent_s_Email__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Photography_Permitted__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Program_Engagement__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Related_Program__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/School_Name__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Things_We_Should_Know__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/What_race_does_your_child_identify_as__c.field-meta.xml, force-app/main/default/objects/Child__c/fields/Which_Pronouns_Does_Your_Child_Prefer__c.field-meta.xml, force-app/main/default/objects/Class__c/fields/CircEsteem_Program__c.field-meta.xml, force-app/main/default/objects/Class__c/fields/Class_Size__c.field-meta.xml, force-app/main/default/objects/Class__c/fields/Contact__c.field-meta.xml, force-app/main/default/objects/Class__c/fields/Maximum_Class_Size__c.field-meta.xml
=> [DevOps Center] Merge WI-010443 to UAT

force-app/main/default/objects/Program_Engagement__c/fields/Engagements_Belong_to_My_Account__c.field-meta.xml, force-app/main/default/objects/Program_Engagement__c/fields/Parent_Contact__c.field-meta.xml, force-app/main/default/objects/Program_Engagement__c/fields/Preferred_Station_Selections_Submitted__c.field-meta.xml, force-app/main/default/objects/Program_Engagement__c/fields/Program_Engagement_Details__c.field-meta.xml, force-app/main/default/objects/Program_Engagement__c/fields/Program_Session__c.field-meta.xml, force-app/main/default/objects/Program_Engagement__c/fields/Status__c.field-meta.xml
=> [DevOps Center] Merge WI-010534 to UAT

force-app/main/default/objects/Program__c/fields/Application_Required__c.field-meta.xml, force-app/main/default/objects/Program__c/fields/Campus__c.field-meta.xml, force-app/main/default/objects/Program__c/fields/Experience_Length__c.field-meta.xml, force-app/main/default/objects/Program__c/fields/Maximun_Age__c.field-meta.xml, force-app/main/default/objects/Program__c/fields/Minimum_Age__c.field-meta.xml, force-app/main/default/objects/Program__c/fields/School__c.field-meta.xml
=> [DevOps Center] Merge WI-010500 to UAT

force-app/main/default/queues/Financial_Aid_Form_Review.queue-meta.xml, force-app/main/default/queues/North_Program_Application_Review.queue-meta.xml, force-app/main/default/queues/West_Program_Application_Review.queue-meta.xml, force-app/main/default/queues/Withdrawal_Request.queue-meta.xml
=> [DevOps Center] Merge WI-010506 to UAT

force-app/main/default/objects/Account/fields/Emergency_Contact_City__c.field-meta.xml, force-app/main/default/objects/Account/fields/Emergency_Contact_First_Name__c.field-meta.xml, force-app/main/default/objects/Account/fields/Emergency_Contact_Last_Name__c.field-meta.xml, force-app/main/default/objects/Account/fields/Emergency_Contact_Phone__c.field-meta.xml, force-app/main/default/objects/Account/fields/Emergency_Contact_Relationship__c.field-meta.xml, force-app/main/default/objects/Account/fields/Emergency_Contact_Same_as_Parent__c.field-meta.xml, force-app/main/default/objects/Account/fields/Emergency_Contact_State__c.field-meta.xml, force-app/main/default/objects/Account/fields/Emergency_Contact_Street__c.field-meta.xml, force-app/main/default/objects/Account/fields/Emergency_Contact_Zip_Code__c.field-meta.xml, force-app/main/default/objects/Program__c/fields/Price__c.field-meta.xml
=> [DevOps Center] Merge WI-010521 to UAT

force-app/main/default/flows/Screen_Flow_CircEsteem_Participant_Intake_Form.flow-meta.xml
=> [DevOps Center] Merge WI-010507 to UAT

force-app/main/default/flows/Screen_Flow_Create_Children.flow-meta.xml
=> [DevOps Center] Merge WI-010513 to UAT

force-app/main/default/flows/Screen_Flow_Financial_Aid_Application.flow-meta.xml
=> [DevOps Center] Merge WI-010503 to UAT

force-app/main/default/groups/All_Managers_Directors.group-meta.xml, force-app/main/default/groups/All_Portal_Users.group-meta.xml, force-app/main/default/groups/All_Program_Coordinators.group-meta.xml
=> [DevOps Center] Merge WI-010528 to UAT

force-app/main/default/quickActions/Account.New_Financial_Aid_Form.quickAction-meta.xml, force-app/main/default/quickActions/Program_Engagement__c.Station_Preferences.quickAction-meta.xml, force-app/main/default/quickActions/Program_Engagement__c.Withdrawal_Request.quickAction-meta.xml, force-app/main/default/quickActions/Program_Session__c.Report_Absence_to_Parents.quickAction-meta.xml
=> [DevOps Center] Merge WI-010530 to UAT

force-app/main/default/objects/Contact/fields/Age__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Allergies__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Authorized_Pickup__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Child_Age__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Ethnicity__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Form_is_Active__c.field-meta.xml, force-app/main/default/objects/Contact/fields/General_Release_Form__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Grade__c.field-meta.xml, force-app/main/default/objects/Contact/fields/My_Household_Contacts__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Parent_Contact__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Photography_Permitted__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Pronouns__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Race__c.field-meta.xml, force-app/main/default/objects/Contact/fields/School_Name__c.field-meta.xml, force-app/main/default/objects/Contact/fields/Things_We_Should_Know__c.field-meta.xml, force-app/main/default/objects/Contact/recordTypes/Child.recordType-meta.xml, force-app/main/default/objects/Contact/recordTypes/Event_Coordinator.recordType-meta.xml, force-app/main/default/objects/Contact/recordTypes/Parent.recordType-meta.xml, force-app/main/default/objects/Contact/recordTypes/Teacher.recordType-meta.xml
=> [DevOps Center] Merge WI-010531 to UAT

force-app/main/default/email/unfiled$public/Child_Absence_Notification_to_Parents.email, force-app/main/default/email/unfiled$public/Child_Absence_Notification_to_Parents.email-meta.xml, force-app/main/default/email/unfiled$public/Financial_Aid_Approved_1706424823942.email, force-app/main/default/email/unfiled$public/Financial_Aid_Approved_1706424823942.email-meta.xml, force-app/main/default/email/unfiled$public/Financial_Aid_Form_Submission.email, force-app/main/default/email/unfiled$public/Financial_Aid_Form_Submission.email-meta.xml, force-app/main/default/email/unfiled$public/Financial_Aid_Rejected_1706424645064.email, force-app/main/default/email/unfiled$public/Financial_Aid_Rejected_1706424645064.email-meta.xml, force-app/main/default/email/unfiled$public/General_Release_Form_with_No_Contact_Found.email, force-app/main/default/email/unfiled$public/General_Release_Form_with_No_Contact_Found.email-meta.xml, force-app/main/default/email/unfiled$public/New_Birthday_Workshop_Release_Form.email, force-app/main/default/email/unfiled$public/New_Birthday_Workshop_Release_Form.email-meta.xml, force-app/main/default/email/unfiled$public/Program_Application_Submission_Notification.email, force-app/main/default/email/unfiled$public/Program_Application_Submission_Notification.email-meta.xml, force-app/main/default/email/unfiled$public/Program_Withdrawal_Request_Alert.email, force-app/main/default/email/unfiled$public/Program_Withdrawal_Request_Alert.email-meta.xml, force-app/main/default/workflows/Form__c.workflow-meta.xml
=> [DevOps Center] Merge WI-010508 to UAT

force-app/main/default/objects/Program_Engagement__c/listViews/My_Active_Program_Engagements.listView-meta.xml, force-app/main/default/objects/Program_Engagement__c/listViews/My_Program_Engagement.listView-meta.xml, force-app/main/default/objects/Program_Session__c/listViews/Programs_Currently_Open_for_Enrollment.listView-meta.xml, force-app/main/default/objects/Program__c/listViews/Active_Programs.listView-meta.xml
=> [DevOps Center] Merge WI-010452 to UAT

force-app/main/default/tabs/Form__c.tab-meta.xml, force-app/main/default/tabs/Program_Engagement__c.tab-meta.xml, force-app/main/default/tabs/Program_Session__c.tab-meta.xml, force-app/main/default/tabs/Program__c.tab-meta.xml, force-app/main/default/tabs/Station__c.tab-meta.xml
=> [DevOps Center] Merge WI-010543 to UAT

force-app/main/default/workflows/Form__c.workflow-meta.xml
=> [DevOps Center] Merge WI-010545 to UAT

force-app/main/default/layouts/Opportunity-Birthday Party%2FWorkshop Layout.layout-meta.xml
=> [DevOps Center] Merge WI-010553 to UAT

force-app/main/default/pathAssistants/Form_Status.pathAssistant-meta.xml, force-app/main/default/pathAssistants/Program_Application_Form_Status.pathAssistant-meta.xml, force-app/main/default/pathAssistants/Withdrawal_Request_Form_Status.pathAssistant-meta.xml
=> [DevOps Center] Merge WI-010558 to UAT

force-app/main/default/flows/Enroll_Program_Engagement.flow-meta.xml, force-app/main/default/flows/Screen_Flow_Create_Children.flow-meta.xml
=> [DevOps Center] Merge WI-010561 to UAT

force-app/main/default/lwc/viewCart/viewCart.js
=> [DevOps Center] Merge WI-010560 to UAT

force-app/main/default/layouts/Program_Session__c-Program Session Layout.layout-meta.xml
=> [DevOps Center] Merge WI-010562 to UAT

force-app/main/default/flows/Program_Engagement_Before_Insert.flow-meta.xml
=> [DevOps Center] Merge WI-010564 to UAT

force-app/main/default/roles/Manager_Director.role-meta.xml, force-app/main/default/roles/Program_Coordinator.role-meta.xml
=> [DevOps Center] Merge WI-010584 to UAT

force-app/main/default/flows/Form_After_Insert.flow-meta.xml
=> [DevOps Center] Merge WI-010605 to UAT

force-app/main/default/flows/Attendance_Screen_Flow.flow-meta.xml, force-app/main/default/objects/Form__c/fields/Attended_Session__c.field-meta.xml
=> [DevOps Center] Merge WI-010641 to UAT

force-app/main/default/email/unfiled$public/New_Product_Purchase_Alert.email, force-app/main/default/email/unfiled$public/New_Product_Purchase_Alert.email-meta.xml, force-app/main/default/flows/Cart_After_Update.flow-meta.xml, force-app/main/default/flows/Form_After_Update.flow-meta.xml, force-app/main/default/flows/Program_Engagement_After_Insert.flow-meta.xml, force-app/main/default/objects/Form__c/fields/Expiration_Date__c.field-meta.xml, force-app/main/default/objects/Program_Engagement__c/fields/Financial_Aid_Form__c.field-meta.xml, force-app/main/default/workflows/Cart__c.workflow-meta.xml
=> [DevOps Center] Merge WI-010994 to UAT

force-app/main/default/quickActions/Program_Engagement__c.Notify_Us_of_Absenses.quickAction-meta.xml, force-app/main/default/workflows/Form__c.workflow-meta.xml
=> [DevOps Center] Merge WI-011031 to UAT

force-app/main/default/quickActions/Program_Engagement__c.Notify_Us_of_Absenses.quickAction-meta.xml
=> [DevOps Center] Merge WI-011042 to UAT

force-app/main/default/objects/Program__c/validationRules/Min_Max_Age_Requirement.validationRule-meta.xml
=> [DevOps Center] Merge WI-011204 to UAT

force-app/main/default/objects/Program_Session__c/fields/Dates__c.field-meta.xml, force-app/main/default/objects/Program_Session__c/fields/Price_Formula__c.field-meta.xml, force-app/main/default/objects/Program_Session__c/fields/Time__c.field-meta.xml, force-app/main/default/objects/Program_Session__c/listViews/Programs_Currently_Open_for_Enrollment.listView-meta.xml
=> [DevOps Center] Merge WI-011205 to UAT

force-app/main/default/classes/CartService.cls, force-app/main/default/classes/ContactService.cls, force-app/main/default/flows/Program_Engagement_After_Insert.flow-meta.xml, force-app/main/default/objects/Cart__c/fields/Contact__c.field-meta.xml
=> [DevOps Center] Merge WI-011222 to UAT

force-app/main/default/flows/Cart_After_Update.flow-meta.xml
=> [DevOps Center] Merge WI-011260 to UAT

force-app/main/default/flows/Cart_After_Update.flow-meta.xml
=> [DevOps Center] Merge WI-011267 to UAT
